In [2]:
import tensorflow as tf
import sys  
sys.path.append("../game") 
from board_class import board
import numpy
print(tf.__version__)

2.0.0


In [3]:
board = board(5)

In [4]:
board.make_board()

In [5]:
print(board.board)

[[ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 -1  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 -1  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [-1  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 -1  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  1 -1  0  0  0  0  0  0]]


In [6]:
class state_action_estimater(tf.keras.Model):
    def __init__(self):
        super(state_action_estimater, self).__init__()
        self.conv1 = tf.keras.layers.Conv2D(input_shape = (10,10), filters = 5, kernel_size = (3,3), strides = (2,2), activation=tf.nn.relu)
        self.flatten = tf.keras.layers.Flatten()
        self.dropout = tf.keras.layers.Dropout(0.5)
        self.concat = tf.keras.layers.Concatenate()
        self.dense1 = tf.keras.layers.Dense(100, activation=tf.nn.relu)
        self.dense1 = tf.keras.layers.Dense(1)
        
        def call(self, state, action, training = False):
            x_conv = self.conv1(state)
            x_flat = self.flatten(x_conv)
            if training:
                x = self.dropout(x_flat)
            x_concat = self.concat(x, action)
            x_dense = self.dense1(x_concat)
            x_dense = self.dense2(X_dense)
            return x_dense



In [7]:
model = state_action_estimater()

In [8]:
model = model.compile(optimizer='adam',
             loss = 'mse')